export const SEARCH_CUSTOMER_BUTTON_ID = 'SEARCH_CUSTOMER_BUTTON_ID_01';
export const SEARCH_CUSTOMER_TAB_01 = 'SEARCH_CUSTOMER_TAB_01';
export const SEARCH_CUSTOMER_TAB_02 = 'SEARCH_CUSTOMER_TAB_02';
export const SEARCH_CUSTOMER_TAB_03 = 'SEARCH_CUSTOMER_TAB_03';
export const SEARCH_CUSTOMER_TAB_04 = 'SEARCH_CUSTOMER_TAB_04';
export const SEARCH_CUSTOMER_INPUT_01 = 'SEARCH_CUSTOMER_INPUT_01';
export const SEARCH_CUSTOMER_INPUT_02 = 'SEARCH_CUSTOMER_INPUT_02';

export const DASHBOARD_BTN_REFRESH = 'DASHBOARD_BTN_REFRESH';
export const DASHBOARD_BTN_CREATE_CONTRACT = 'DASHBOARD_BTN_CREATE_CONTRACT';
export const DASHBOARD_FILTER_BTN_SEARCH = 'DASHBOARD_FILTER_BTN_SEARCH';
export const DASHBOARD_FILTER_BTN_RESET = 'DASHBOARD_FILTER_BTN_RESET';

export const REJECT_CONTRACT_INPUT = 'REJECT_CONTRACT_INPUT';
export const REJECT_CONTRACT_BUTTON_OK = 'REJECT_CONTRACT_BUTTON_OK';
export const CANCEL_CONTRACT_DROPDOWN = 'CANCEL_CONTRACT_DROPDOWN';
export const CANCEL_CONTRACT_BUTTON_OK = 'CANCEL_CONTRACT_BUTTON_OK';

export const CREATE_CONTRACT_SAVE_DRAFT_BUTTON_ID = 'CREATE_CONTRACT_SAVE_DRAFT_BUTTON_ID';
export const CREATE_CONTRACT_EDIT_BUTTON_ID = 'CREATE_CONTRACT_EDIT_BUTTON_ID';
export const CREATE_CONTRACT_APPROVE_BUTTON_ID = 'CREATE_CONTRACT_APPROVE_BUTTON_ID';
export const CREATE_CONTRACT_PENDING_COMFIRMATION_CONFIRM_BUTTON_ID =
	'CREATE_CONTRACT_PENDING_COMFIRMATION_CONFIRM_BUTTON_ID';
export const CREATE_CONTRACT_DROPDOWN_CONTRACT_ID = 'CREATE_CONTRACT_DROPDOWN_CONTRACT_ID';
export const CREATE_CONTRACT_BOX_DATA_SYSTEM_ID = 'CREATE_CONTRACT_BOX_DATA_SYSTEM_ID';
export const CREATE_CONTRACT_SUBMIT_BUTTON_ID = 'CREATE_CONTRACT_SUBMIT_BUTTON_ID';
